name: Deploy
on:
  push:
    branches:
      - backend

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Build
        run: make build
      - name: Test with the Go CLI
        run: make test
